services:
  app:
    image: islandora/alpaca:latest
    container_name: alpaca
    ports:
      - "8080:8080"
    depends_on:
      - activemq

  activemq:
    image: apache/activemq-classic:latest
    container_name: activemq
    ports:
      - "6163:61613" # STOMP
      - "6166:61616" # JMS
      - "8161:8161"   # Web console

  awstranscribe:
    image: islandora/awstranscribe:latest
    container_name: awstranscribe
    expose:
      - 8000

  ffmpeg:
    image: islandora/ffmpeg:latest
    container_name: ffmpeg
    expose:
      - 8000
    environment:
      - SKIP_JWT_VERIFY=true

  imagemagick:
    image: islandora/imagemagick:latest
    container_name: imagemagick
    expose:
      - 8000
    environment:
      - SKIP_JWT_VERIFY=true
    
  tesseract:
    image: islandora/tesseract:latest
    container_name: tesseract
    expose:
      - 8080
    environment:
      - SKIP_JWT_VERIFY=true

  fits:
    image: islandora/fits:latest
    container_name: fits
    expose:
      - 8080